
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simphy;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFrame;

/**
 *
 * @author Madeyedexter
 */
public class BlockJDialog extends javax.swing.JDialog 
{
    private final DrawingPanel drawingPanel;
    /**
     * Creates new form CircleJDialog
     * @param parent
     * @param modal
     * @param p
     */
    public BlockJDialog(java.awt.Frame parent, boolean modal, DrawingPanel p) 
    {
        super(parent, modal);
        drawingPanel=p;
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        blockID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        blockPosition = new javax.swing.JTextField();
        blockWidth = new javax.swing.JTextField();
        blockMass = new javax.swing.JTextField();
        blockDamping = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        blockCreateButton = new javax.swing.JButton();
        blockCancelButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        blockHeight = new javax.swing.JTextField();
        fixedCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        blockColor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name:");

        blockID.setText("BlockID");
        blockID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Position:");

        jLabel3.setText("Width:");

        jLabel4.setText("Mass:");

        jLabel5.setText("Damping:");

        blockPosition.setText("TOP-LEFT(x,y)");
        blockPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockPositionActionPerformed(evt);
            }
        });

        blockWidth.setText("px");
        blockWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockWidthActionPerformed(evt);
            }
        });

        blockMass.setText("Kg");
        blockMass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockMassActionPerformed(evt);
            }
        });

        blockDamping.setText("factor");
        blockDamping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockDampingActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Create New Item: Block");

        blockCreateButton.setText("Create");
        blockCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockCreateButtonActionPerformed(evt);
            }
        });

        blockCancelButton.setText("Cancel");
        blockCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockCancelButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Height:");

        blockHeight.setText("px");
        blockHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockHeightActionPerformed(evt);
            }
        });

        fixedCheckBox.setText("Fixed");
        fixedCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fixedCheckBoxStateChanged(evt);
            }
        });
        fixedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedCheckBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Color");

        blockColor.setEditable(false);
        blockColor.setBackground(new java.awt.Color(0, 153, 153));
        blockColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blockColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blockColorMouseClicked(evt);
            }
        });
        blockColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blockHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(blockCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(blockCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blockDamping, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blockMass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blockWidth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blockPosition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blockID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(infoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixedCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blockColor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockDamping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fixedCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockCreateButton)
                    .addComponent(blockCancelButton))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blockIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockIDActionPerformed

    private void blockPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockPositionActionPerformed

    private void blockWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockWidthActionPerformed

    private void blockMassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockMassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockMassActionPerformed

    private void blockDampingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockDampingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockDampingActionPerformed

    private void blockCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockCreateButtonActionPerformed
        String ID=blockID.getText();
        String[] position=blockPosition.getText().split(",");
        String m=blockMass.getText();
        String w=blockWidth.getText();
        String h=blockHeight.getText();
        String d=blockDamping.getText();
        boolean fixed=fixedCheckBox.isSelected();
        Color c=blockColor.getBackground();
        int x,y,mass,width,height;
        float damping;
        if(Items.exists_id(ID))
        {
            infoLabel.setText("ID already exists.");
            return;
        }
        try
        {
            x=Integer.parseInt(position[0]);
            y=Integer.parseInt(position[1]);
            width=Integer.parseInt(w);
            height=Integer.parseInt(h);
            mass=Integer.parseInt(m);
            damping=Float.parseFloat(d);
        }
        catch(NumberFormatException e)
        {
            infoLabel.setText("Unable to parse into valid Numeric Value");
            return;
        }
        if(height>DrawingPanel.HEIGHT_DP/2 || width>DrawingPanel.WIDTH_DP/2)
        {
            infoLabel.setText("Size of Object Excedes Maximum Limit.");
            return;
        }
        Block b=new Block(ID,width,height,mass,fixed,x,y,damping,c);
        Items.addBlock(b);
        Items.addid(ID);
        if(!DrawingPanel.RUNNING)
            drawingPanel.draw();
        dispose();
        
    }//GEN-LAST:event_blockCreateButtonActionPerformed

    private void blockCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockCancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_blockCancelButtonActionPerformed

    private void blockHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockHeightActionPerformed

    private void blockColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockColorActionPerformed
        
    }//GEN-LAST:event_blockColorActionPerformed

    private void fixedCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fixedCheckBoxStateChanged
        
    }//GEN-LAST:event_fixedCheckBoxStateChanged

    private void fixedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedCheckBoxActionPerformed
        if(blockColor.isEnabled())
        {
            blockColor.setEnabled(false);
            blockColor.setBackground(Color.LIGHT_GRAY);
        }
        else
        {
            blockColor.setEnabled(true);
            blockColor.setBackground(Color.CYAN);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fixedCheckBoxActionPerformed

    private void blockColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blockColorMouseClicked
        Color c=JColorChooser.showDialog(this, "Choose Item Color", blockColor.getBackground());
        if(c!=null)
            blockColor.setBackground(c);
    }//GEN-LAST:event_blockColorMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blockCancelButton;
    private javax.swing.JTextField blockColor;
    private javax.swing.JButton blockCreateButton;
    private javax.swing.JTextField blockDamping;
    private javax.swing.JTextField blockHeight;
    private javax.swing.JTextField blockID;
    private javax.swing.JTextField blockMass;
    private javax.swing.JTextField blockPosition;
    private javax.swing.JTextField blockWidth;
    private javax.swing.JCheckBox fixedCheckBox;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
