/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simphy;

import java.awt.Color;
import java.util.Vector;
import javax.swing.JColorChooser;
import javax.swing.JFrame;

/**
 *
 * @author Madeyedexter
 */
public class CircleJDialog extends javax.swing.JDialog 
{
    private final DrawingPanel drawingPanel;
    /**
     * Creates new form CircleJDialog
     * @param parent
     * @param modal
     * @param p
     */
    public CircleJDialog(java.awt.Frame parent, boolean modal, DrawingPanel p) 
    {
        super(parent, modal);
        drawingPanel=p;
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldCircleID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldCirclePosition = new javax.swing.JTextField();
        fieldCircleRadius = new javax.swing.JTextField();
        fieldCircleMass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        circleCreateButton = new javax.swing.JButton();
        circleCancelButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldCircleColor = new javax.swing.JTextField();
        staticCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setText("Name:");

        fieldCircleID.setText("Circle"+Items.numCircles());
        fieldCircleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCircleIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Position:");

        jLabel3.setText("Radius:");

        jLabel4.setText("Mass:");

        fieldCirclePosition.setText("10,10");
        fieldCirclePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCirclePositionActionPerformed(evt);
            }
        });

        fieldCircleRadius.setText("1");
        fieldCircleRadius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCircleRadiusActionPerformed(evt);
            }
        });

        fieldCircleMass.setText("1");
        fieldCircleMass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCircleMassActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Create New Item: Circle");

        circleCreateButton.setText("Create");
        circleCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleCreateButtonActionPerformed(evt);
            }
        });

        circleCancelButton.setText("Cancel");
        circleCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleCancelButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Color:");

        fieldCircleColor.setEditable(false);
        fieldCircleColor.setBackground(new java.awt.Color(255, 0, 51));
        fieldCircleColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fieldCircleColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldCircleColorMouseClicked(evt);
            }
        });
        fieldCircleColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCircleColorActionPerformed(evt);
            }
        });

        staticCheckBox.setText("Static");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(circleCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(circleCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCircleMass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCircleRadius, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCirclePosition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCircleID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldCircleColor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(staticCheckBox)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCircleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCirclePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCircleRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCircleMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCircleColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(staticCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(circleCancelButton)
                    .addComponent(circleCreateButton))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCircleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCircleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCircleIDActionPerformed

    private void fieldCirclePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCirclePositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCirclePositionActionPerformed

    private void fieldCircleRadiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCircleRadiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCircleRadiusActionPerformed

    private void fieldCircleMassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCircleMassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCircleMassActionPerformed

    private void circleCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleCreateButtonActionPerformed
        String ID=fieldCircleID.getText();
        String[] position=fieldCirclePosition.getText().split(",");
        String m=fieldCircleMass.getText();
        String r=fieldCircleRadius.getText();
        Color color=fieldCircleColor.getBackground();
        float x,y,mass,radius;
        if(Items.exists_id(ID))
        {
            infoLabel.setText("ID already exists.");
            return;
        }
        try
        {
            x=Float.parseFloat(position[0]);
            y=Float.parseFloat(position[1]);
            radius=Float.parseFloat(r);
            mass=Float.parseFloat(m);
            
        }
        catch(NumberFormatException e)
        {
            infoLabel.setText("Unable to parse into valid Numeric Value");
            return;
        }
        Circle c=new Circle(ID,radius,new Vector2D(x,y),mass);
        Items.addCircle(c);
        Items.addid(ID);
        if(!DrawingPanel.RUNNING)
        drawingPanel.draw();
            dispose();
        
    }//GEN-LAST:event_circleCreateButtonActionPerformed

    private void circleCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleCancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_circleCancelButtonActionPerformed

    private void fieldCircleColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCircleColorActionPerformed
        
    }//GEN-LAST:event_fieldCircleColorActionPerformed

    private void fieldCircleColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCircleColorMouseClicked
        Color c=JColorChooser.showDialog(this,"Choose Item Color", fieldCircleColor.getBackground());
        if(c!=null)
        fieldCircleColor.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCircleColorMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circleCancelButton;
    private javax.swing.JButton circleCreateButton;
    private javax.swing.JTextField fieldCircleColor;
    private javax.swing.JTextField fieldCircleID;
    private javax.swing.JTextField fieldCircleMass;
    private javax.swing.JTextField fieldCirclePosition;
    private javax.swing.JTextField fieldCircleRadius;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox staticCheckBox;
    // End of variables declaration//GEN-END:variables

}
