/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package simphy;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Madeyedexter
 */
public class PlaneJDialog extends javax.swing.JDialog {

    private int x1,y1,x2,y2,x3,y3;
    private boolean errorFlag=true;
    private final String message="Invalid value for Points!";
    private final DrawingPanel drawingPanel;
    /**
     * Creates new form PlaneJDialog
     */
    public PlaneJDialog(java.awt.Frame parent, boolean modal, DrawingPanel dp) {
        super(parent, modal);
        initComponents();
        String[] p1=p1Field.getText().split(",");
        String[] p2=p2Field.getText().split(",");
        
        drawingPanel=dp;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        p1Label = new javax.swing.JLabel();
        p1Field = new javax.swing.JTextField();
        planeCreateButton = new javax.swing.JButton();
        planeCancelButton = new javax.swing.JButton();
        p1Label1 = new javax.swing.JLabel();
        p2Field = new javax.swing.JTextField();
        notifPanel = new javax.swing.JPanel()
        {
            @Override
            public void paintComponent(Graphics g)
            {
                g.setColor(Color.WHITE);
                g.fillRect(0,0,getWidth(),getHeight());
                if(errorFlag)
                {
                    g.drawString(message,getWidth()/3,getHeight()/2);
                }
                else{
                    Graphics2D g2=(Graphics2D)g;
                    g2.setColor(Color.GRAY);
                    int width=x3-x2;
                    int height=y3-y1;
                    float scaleX=getWidth()/width;
                    float scaleY=getHeight()/height;
                    int X1=2,X2=2+(int)(width*scaleX),X3=2;
                    int Y3=getHeight()-5,Y2=getHeight()-5,Y1=getHeight()-(2+(int)(height+scaleY));
                    g2.fillPolygon(new int[]{X1,X2,X3},new int[]{Y1,Y2,Y3},3);
                }
            }

        }
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setText("Create New Item: Inclined Plane");

        nameLabel.setText("Name:");

        idField.setText("Plane"+Items.numPlanes());
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        p1Label.setText("Point 1:");

        p1Field.setText("10,10");
        p1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1FieldActionPerformed(evt);
            }
        });
        p1Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                p1FieldFocusLost(evt);
            }
        });

        planeCreateButton.setText("Create");
        planeCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planeCreateButtonActionPerformed(evt);
            }
        });

        planeCancelButton.setText("Cancel");
        planeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planeCancelButtonActionPerformed(evt);
            }
        });

        p1Label1.setText("Point 2:");

        p2Field.setText("20,20");
        p2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2FieldActionPerformed(evt);
            }
        });
        p2Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                p2FieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout notifPanelLayout = new javax.swing.GroupLayout(notifPanel);
        notifPanel.setLayout(notifPanelLayout);
        notifPanelLayout.setHorizontalGroup(
            notifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        notifPanelLayout.setVerticalGroup(
            notifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(planeCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(planeCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notifPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(p1Label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(p2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(titleLabel)
                            .addGap(0, 12, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameLabel)
                                .addComponent(p1Label))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(p1Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(22, 22, 22)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notifPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planeCreateButton)
                    .addComponent(planeCancelButton))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(293, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void p1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1FieldActionPerformed

    private void planeCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planeCreateButtonActionPerformed
        String ID=idField.getText();
        String[] p1=p1Field.getText().split(",");
        String[] p2=p2Field.getText().split(",");
        
        
        //create plane
        Plane plane=new Plane(new Vector2D(x1,y1),new Vector2D(x2,y2),new Vector2D(x3,y3));
        Items.addPlane(plane);
        Items.addid(ID);
        
        if(!DrawingPanel.RUNNING)
            drawingPanel.draw();
        dispose();

    }//GEN-LAST:event_planeCreateButtonActionPerformed

    private void planeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planeCancelButtonActionPerformed
        this.dispose();
        if(!DrawingPanel.RUNNING)
            drawingPanel.draw();
    }//GEN-LAST:event_planeCancelButtonActionPerformed

    private void p2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2FieldActionPerformed

    private void p1FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p1FieldFocusLost
        errorFlag=false;
        String[] p1=p1Field.getText().split(",");
        
        
    }//GEN-LAST:event_p1FieldFocusLost

    private void p2FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p2FieldFocusLost
        errorFlag=false;
        
    }//GEN-LAST:event_p2FieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel notifPanel;
    private javax.swing.JTextField p1Field;
    private javax.swing.JLabel p1Label;
    private javax.swing.JLabel p1Label1;
    private javax.swing.JTextField p2Field;
    private javax.swing.JButton planeCancelButton;
    private javax.swing.JButton planeCreateButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
